### ISSUE TITLE
app.diagrams.net is phased out

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#230]
Hi Arnaud,
When editing the diagram via flowcharting, I recently get the warning that edit with app.diagrams.net is phased out, guess we need to move to embed.diagrams.net instead. See warning below
![image](https://user-images.githubusercontent.com/6523124/96272634-a58b9500-0fce-11eb-878a-5eaaf267b3e2.png)
Kind regards,
Dennis

**Comment by algenty** [comment]
Hi Dennis,
I have a discussions with draw.io teams, i cant i use this url because it not works.
We try to have a solution

**Comment by bijwaard** [comment]
Hi Arnaud,
I hope draw.io fixes their new URL before the other one is phased out, or another solutiont if not. Editing the diagram from flowcharting is quite a helpful feature.
Kind regards,
Dennis

**Comment by algenty** [comment]
Fixed in 0.9.1 snapshot with 'https://embed.diagrams.net/'

**Comment by MxPie200** [comment]
@algenty 
I'm still having the same issue as @bijwaard , in 2023.
I can open the drawing and its showing the mentioned warning:
![grafik](https://user-images.githubusercontent.com/81758431/233836596-a7c9f312-f58e-4d32-af03-e44f2c3255bc.png)

But if i make any changes to the Flowchart, the whole thing disappeared after closing the editor:

![grafik](https://user-images.githubusercontent.com/81758431/233836580-eb6d49fc-f331-4251-94a1-2edee971ede4.png)

How can I edit my drawing / how can we move to embed.diagrams.net ?
Changing the url in the "Source Content" does not work:
![grafik](https://user-images.githubusercontent.com/81758431/233836733-be605234-463e-4689-b68e-4ff2afb2cbdd.png)

I really like the Flowchart extension and would be great to hear about a fix for my issue.

**Comment by bijwaard** [comment]
Works for me, see my answer in #406
