### ISSUE TITLE
hyperlink text appears in white over flowchart

### ISSUE THREAD

**Issue by bijwaard** [algenty/grafana-flowcharting#45]
Hi Arnaud,
I created two links in my flowcharting diagram, one via draw.io on the logo icon, and one via a rule on the business building icon. Both are shown in white over the diagram, both when editing rules (first figure, below its icons) and also when in view mode (second figure, once on the right of logo icon, three times on the right&above building icon).

This started after using the inspector, I only seem to be able to get rid of it by re-loading the grafana web-page.

Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/65969661-765ac200-e465-11e9-94f9-909fe8af721b.png)
![image](https://user-images.githubusercontent.com/6523124/65969733-938f9080-e465-11e9-99ba-9d7d6c2b2d96.png)

**Comment by algenty** [comment]
Hi Dennis,
I know this bug, for me it's only during the conception , if you save and reload, the text disappears.
i need more test for this bug

BR

**Comment by bijwaard** [comment]
It seems to be related to the inspector, after page reload and using the inspector for the relevant icons the white hyperlinks appeared again.

**Comment by bijwaard** [comment]
Also just happened while adding a link to a rule.

**Comment by bijwaard** [comment]
As a side node, only the first link (CT2:L1) has an active hyperlink when I configure multiple link objects. The other 3 are not clickable.
![image](https://user-images.githubusercontent.com/6523124/65973813-3945fe00-e46c-11e9-8661-7af5b6c87681.png)

**Comment by algenty** [comment]
Which version do you use?

**Comment by bijwaard** [comment]
This is with the 0.40 release, I look forward to the 0.50 fixes;-)

**Comment by algenty** [comment]
Dennis,
any news ?

**Comment by bijwaard** [comment]
No more news for these bugs, both white hyperlinks and multi-link mappings problems are still there.

**Comment by algenty** [comment]
fixed in lat 0.5.0

**Comment by bijwaard** [comment]
Hi Arnaud,
Great, the white hyperlink happens less frequent now. However, I still get it when I quickly hover over the link mapping IDs a number of times.
Kind regards,
Dennis

**Comment by bijwaard** [comment]
Hi Arnaud,
I apparently didn't install the snapshot properly, I had multiple versions with different names in /var/lib/grafana/plugins. I now moved away the 0.4.0 version, restarted grafana and the multiple links work as well as the variable selection. Great work!!
Dennis

**Comment by algenty** [comment]
next snapshot doesn't  reset zoom when datas refreshed
it coming soon, i need you to test it, you are my favorite tester :)

**Comment by bijwaard** [comment]
Hi Arnaud,
I'ld be happy to test it, it would improve zoom functionality, I guess I noticed this issue some time ago while testing zoom.
Kind regards,
Dennis

**Comment by bijwaard** [comment]
Hi Arnaud,
Zoom level now persists when dashboard refreshes its metrics, tested in firefox with double-click zoom, and in chromium with most zoom-abilities. Great work! 
Some related issues:
- zooming with mouse still doesn't work in firefox, all icons disappear as commented earlier in one of the zoom-related tickets.
- Variable selection resets the zoom level.
- mouse-wheel scroll has some weird side-effects in chrome with the background, see figure below. A partly transparent background (as configured in draw.io) is shown instead of the configured light-blue background under flowcharting.

Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/66427257-ddebb100-ea13-11e9-9330-6d5d4281801c.png)

**Comment by algenty** [comment]
hi Dennis
thx for your feebacks
i kowns these problems when scale is on
i'll try to correct it

br
Arnaud

**Comment by algenty** [comment]
Zoom et background resoved in last snapshot

**Comment by bijwaard** [comment]
Hi Arnaud,
After double click I cannot scroll anymore, no wonder that the background issue does not appear anymore. I liked being able to scroll through the rest of the flowchart after zoom, especially on firefox where I cannot (yet) zoom with the mouse because all graphics get lost. Now I have to create a number of areas in draw.io to zoom to...
Kind regards,
Dennis

**Comment by algenty** [comment]
thx for this feedback

**Comment by algenty** [comment]
I share a screenshot of next version, not available at the moment, maybe this week-end
![tooltip_graph_ani_2](https://user-images.githubusercontent.com/47012725/66698148-b0d12400-ecdb-11e9-9377-64bc483b8c21.gif)

**Comment by bijwaard** [comment]
Hi Arnaud,

Very nice to see the graphs from the chart, I can't wait;-)

Dennis

⁣Sent from TypeApp ​

**Comment by algenty** [comment]
Hi Dennis,
This version is available in download section. i've fixed zoom in firefox and edge.
![tooltip_graph](https://user-images.githubusercontent.com/47012725/66717066-41d7f600-edd5-11e9-93da-cab90143c5db.gif)

https://twitter.com/gf_flowcharting/status/1183386365175746562

BR

**Comment by bijwaard** [comment]
Hi Arnaud,

The graph tooltips work like a charm on graph icons! Also zooming in firefox works. You've been busy, good work!

The tooltips however do not seem to work on lines connecting icons.

Kind regards,
Dennis

**Comment by algenty** [comment]
Yeah !!! it's fantastic
Thanks for this first feedback !! I am very happy
I add "scaling for Y value" on roadmap.
I dont understand why it not work on line or arrow, i'll try it

To show multi graph in the same tooltip, you need multi rules/series on the same object.
I don't understand the graph, it's your home ?

BR,
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud,
The graph is indeed a lab-home with a 3-phase power connection to the grid at the top and a single-phase and tri-phase inverter at the bottom all measured with our [LV-Sensors](https://smartstatetechnology.nl/#solutions). Next step in the United-Grid project is to also measure the substation;-) In the substation, multi-rules/series and tooltip graphs would be very nice.

Yes you can use my screenshot for twitter.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Hi Arnaud,
I'm having some trouble getting the multi-metric graphs to work. I've added a regex that selects 3 metrics in the Business rule (/CT:P_L[123]-active/), I now see 4 values in my chart above the office icon where the top-one seems to be the sum of the other three, and I only see one graph for the third metric (bottom value above office icon is same as in graph).
I tried fiddling with grouping in the metrics regex and tried to re-use them in the tooltip label, but this doesn't seem to work, e.g. metric /\(CT:P_L[123]-active\)/ and label \1, empty label doesn't show label in tooltip
Kind regards,
Dennis
![image](https://user-images.githubusercontent.com/6523124/66734978-62e82780-ee65-11e9-866b-268d53b8ebdd.png)

**Comment by algenty** [comment]
Ok, i understand. I'll try to fix it
it works if you have 4 rules (1 rule : 1 value) instead 1 rules 4 values
Graph is based on the name of label (uniq), each value replace the previous value and graph becaus label is the same.
Its a good issue for me, I never thought you could use flowcharting like that. 
Can you create a new issue for it ?

BR
Arnaud
